version: "3.9"
services: 
  bot:
    build: .
    image: "leadpogrommer/telehaskell"
    depends_on:
      - db
      - telegram-bot-api
    expose: 
      - "8080"
    restart: always
    environment: 
      BOT_TOKEN:
      IN_DOCKER: "1"
  
  db:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - db-data:/data/db
    logging:
      driver: none
  
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_LOCAL: "1"
    expose:
      - "8081"

volumes:
  db-data: